# Generated by Django 5.0 on 2024-01-09 18:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=50)),
                ('fPrenom', models.CharField(default='', max_length=50)),
                ('fNai', models.CharField(default=0.0)),
                ('fRegime', models.CharField(default=0.0)),
                ('fSitu', models.CharField(default='', max_length=50)),
                ('fSexe', models.CharField(default='', max_length=50)),
                ('fEmail', models.CharField(default='', max_length=50)),
                ('fPays_de_naissance', models.CharField(default='', max_length=50)),
                ('fville', models.CharField(default='', max_length=50)),
                ('fAdresse', models.CharField(default='', max_length=100)),
                ('fAdresse2', models.CharField(default='', max_length=100)),
                ('fCpo', models.CharField(default='', max_length=50)),
                ('ftel', models.CharField(default='', max_length=50)),
                ('ftel1', models.CharField(default='', max_length=50)),
                ('fprof', models.CharField(default='', max_length=50)),
                ('fvilN', models.CharField(default='', max_length=50)),
                ('fCP', models.CharField(default='', max_length=50)),
                ('fCom', models.CharField(default='', max_length=50)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('fstatut', models.CharField(default='en attente', max_length=50)),
                ('fprixTotale', models.FloatField(default=0.0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContratForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Société_a_résilier', models.CharField(default='', max_length=50)),
                ('Nom_assurance', models.CharField(default='', max_length=50)),
                ('Code_postale', models.CharField(default='', max_length=50)),
                ('Adresse', models.CharField(default='', max_length=50)),
                ('Ville', models.CharField(default='', max_length=50)),
                ('Type_de_Résiliation', models.CharField(default='', max_length=50)),
                ('Type_de_contrat', models.CharField(default='', max_length=50)),
                ('N_contrat', models.CharField(default='', max_length=50)),
                ('N_SS', models.CharField(default='', max_length=50)),
                ('Nombre_de_contrat', models.IntegerField(default=0)),
                ('N_RAR', models.CharField(default='', max_length=50)),
                ('Date_effet', models.CharField(default='', max_length=50)),
                ('Date_de_résiliation', models.CharField(default='', max_length=50)),
                ('Commentaire', models.CharField(default='')),
                ('user_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='custom_authentication.userform')),
            ],
        ),
    ]
