# Generated by Django 5.0 on 2023-12-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
