# Generated by Django 5.0 on 2024-01-09 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_authentication', '0002_remove_contratform_user_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratform',
            name='user_form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='custom_authentication.userform'),
        ),
    ]
