# Generated by Django 5.0 on 2024-01-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_authentication', '0003_contratform_user_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='factive',
            field=models.CharField(default='', max_length=50),
        ),
    ]
