# Generated by Django 5.0 on 2024-01-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_authentication', '0004_userform_factive'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratform',
            name='fprixTotale',
            field=models.FloatField(default=0.0),
        ),
    ]
