# Generated by Django 5.0 on 2024-01-10 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_authentication', '0005_contratform_fprixtotale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratform',
            old_name='fprixTotale',
            new_name='prixTotale',
        ),
    ]
