# Generated by Django 5.0 on 2024-01-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_authentication', '0006_rename_fprixtotale_contratform_prixtotale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='fstatut',
            field=models.CharField(default='', max_length=50),
        ),
    ]
